name: Snake
main: ca.shaw.andrewbailey.Snake
version: 0.1
commands:
   snake:
      description: CRICKEY THATS A SNAKE
      usage: /snake
      permission: snake.create
      permission-message: You don't have permission to do this.